---
- name: Install Docker on EC2 Instances
  hosts: testserver
  remote_user: devopsadmin
  become: true
  tasks:
    tasks:
    - name: Install Docker
      yum:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add devopsadmin to docker group
      user:
        name: devopsadmin
        groups: docker
        append: yes

    - name: Restart Docker service
      systemd:
        name: docker
        state: restarted
