---
- name: Install Docker on EC2 Instances
  hosts: testserver
  remote_user: devopsadmin
  become: true
  tasks:
    - name: Install Docker
      shell: |
        sudo amazon-linux-extras install docker -y
        sudo systemctl start docker
        sudo usermod -aG docker devopsadmin
        sudo systemctl enable docker