---
- name: Deploy Container to QA server
  hosts: testserver
  remote_user: devopsadmin
  become: true
  vars: 
    docker_registry: docker.io
    dockerhub_repo: dashshishir/devopsedu
    docker_image_tag: latest
  tasks:
    - name: Pull the docker image
      shell: |
        docker pull {{ docker_registry }}/{{ dockerhub_repo }}:{{ docker_image_tag }}
    - name: Stop and Remove the existing container
      shell: |
        docker rm -f $(docker ps -aq)
    - name: Run the container
      shell: |
        docker run -d -p 8080:80 dashshishir/devopsedu:latest


